SELECT *
FROM [SQL Tutorial].dbo.EmployeeDemographics
UNION ALL
SELECT *
FROM [SQL Tutorial].DBO.WAREHOUSEEMPLOYEEDEMOGRAPHICS
ORDER BY EmployeeID

--BE CAREFUL B/C IN BOTH TABLES HAVE DIFFERENT COLUMN NAMES
--BUT SINCE EMPLOYEEID IS AN INT IT MATCHES, FIRSTNAME IS A STRING SO IT MATCHES JOBTITLE,
--AND AGE AND SALARY ARE INTS SO THEY MATCH BUT ALL ARE DIFFERENT DATA SO IT'S WRONG
--THE COLUMN NAMES MUST MATCH WHEN USING UNIONS
SELECT EmployeeID, FirstName, AGE
FROM [SQL Tutorial].dbo.EmployeeDemographics
UNION ALL
SELECT EmployeeID, JobTitle, Salary
FROM [SQL Tutorial].DBO.EmployeeSalary
ORDER BY EmployeeID


--SELECT *
--FROM [SQL Tutorial].DBO.EmployeeDemographics
--FULL OUTER JOIN [SQL Tutorial].DBO.WAREHOUSEEMPLOYEEDEMOGRAPHICS
--	ON EmployeeDemographics.EmployeeID =
--	WAREHOUSEEMPLOYEEDEMOGRAPHICS.EMPLOYEEID