--LEFT OUTER JOIN TO DISPLAY ALL PERSONS WHETHER EMPLOYEES OR NOT EMPLOYEES
-- THE LEFT JOIN NAMING CONVENTION REFERS TO THE FIRST TABLE OR LEFT MOST TABLE
-- SO A LEFT JOIN WILL TREAT THIS AS OUR PRIMARY TABLE THAT WE WANT TO SEE ALL RECORDS FROM
SELECT A.[BusinessEntityID]
      ,A.[FirstName]
      ,A.[LastName]			-- NOTE TO STICK WITH LEFT JOINS ALWAYS..VERY RARELY 
	  ,B.[JobTitle]			-- THAT RIGHT JOINS ARE USED
	  ,B.[VacationHours],
	  B.[SickLeaveHours]
  FROM [AdventureWorks2019].[Person].[Person] A	--THIS IS OUR LEFT TABLE OR PRIMARY TABLE
   LEFT OUTER JOIN [AdventureWorks2019].[HumanResources].[Employee] B
  ON A.[BusinessEntityID] = B.[BusinessEntityID]
  WHERE A.[FirstName] = 'John'